source "https://rubygems.org"

ruby "2.6.2"

gem "bourbon"
gem "builder"
gem "middleman"
gem "middleman-aria_current"
gem "middleman-autoprefixer"
gem "middleman-inline_svg"
gem "middleman-livereload"
gem "middleman-minify-html"
gem "redcarpet"
gem "sass"
gem "sassc"
